### ISSUE TITLE
License

### ISSUE THREAD

**Issue by feamsr00** [apimatic/core-lib-php#15]
Hi There,

3 quick questions:

1. What does "reference" mean for this license in "plain language"? 
2. Can you link to this "reference" from an OS project that a third party downloads for example from composer? (1st party: Apimatic; 2nd party: Consumer of Core in 'MyLib'; 3rd Party: End User of 'MyLib')
3. What was the rational for not using the MIT License here?

Thanks for any insight you could provide!

**Comment by thehappybug** [comment]
@feamsr00 Hey. Please reach out to licensing@apimatic.io for more details.
