### ISSUE TITLE
Consider changing the namespace to Apimatic\Core?

### ISSUE THREAD

**Issue by pkly** [apimatic/core-lib-php#63]
Hello,

I've noticed that the repositories
https://github.com/apimatic/core-lib-php
https://github.com/apimatic/core-interfaces-php
https://github.com/apimatic/unirest-php

Do not contain a "vendor" namespace beginning and are rather generic.
Would you maybe consider updating that in a future release of said libraries?

Most of the biggest vendors do it this way and it would clean up any misconceptions about what these libraries are.

**Comment by asadali214** [comment]
Hi @pkly,

Thank you for your valuable input here! We also believe this approach aligns with community standards, as it's reflected in the practices followed by the most popular packages on Packagist.

For now, we've added this suggestion to our backlog and tagged it as an idea. We'll keep this under consideration as we continue to evaluate and improve.

Thanks again for sharing!
